options:
  docker: true

pipelines:
  default:
    - step:
        script:
          - export IMAGE_NAME=atlassianlabs/docker-node-jdk-chrome-firefox:latest
          - export DOCKER_BUILDKIT=1
          - docker buildx build --provenance=true --sbom=true -t $IMAGE_NAME .

  branches:
    master:
      - step:
          script:
            - export IMAGE_NAME=atlassianlabs/docker-node-jdk-chrome-firefox:latest
            - export DOCKER_BUILDKIT=1
            - docker buildx create --use
            - docker buildx build --attest=provenance=mode=max --attest=sbom=spdx -t $IMAGE_NAME .
            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            - docker push $IMAGE_NAME

  custom:
    deployment-to-hub-docker:
      - step:
          script:
            - export DATE=`date +%Y-%m-%d`
            - export IMAGE_NAME=atlassianlabs/docker-node-jdk-chrome-firefox:$DATE
            - export DOCKER_BUILDKIT=1
            - docker buildx create --use
            - docker buildx build --attest=provenance=mode=max --attest=sbom=spdx -t $IMAGE_NAME .
            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            - docker push $IMAGE_NAME
